import type { Metadata } from 'next';
import './globals.css';
import { Patua_One, Inter } from 'next/font/google';
import Nav from './components/Nav';
import { auth } from '@/auth';
import Hydrate from './components/Hydrate';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const inter = Inter({ weight: '400', subsets: ['latin'], display: 'swap', variable: '--font-inter' });
const patua = Patua_One({ weight: '400', subsets: ['latin'], display: 'swap', variable: '--font-patua' });

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  return (
    <html lang="en" className={`${inter.variable} ${patua.variable}`}>
      <body className="bg-orange-50 text-stone-700 font-inter">
        <Hydrate>
          <Nav user={session?.user} expires={session?.expires as string} />
          <main className="px-2 sm:px-4">
            <div className="mx-auto max-w-6xl">{children}</div>
          </main>
        </Hydrate>
      </body>
    </html>
  );
}
